//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLabours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_UsedStock
    {
        public Nullable<int> Used_stock { get; set; }
        public int SERVICEPROVIDERID { get; set; }
        public Nullable<int> SERVICEPLANID { get; set; }
    }
}
