//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLabours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherAssignedToLabour
    {
        public int VoucherAssignID { get; set; }
        public int VOUCHERID { get; set; }
        public string LabourID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    }
}
