// <auto-generated />
namespace SmartLabours.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HelpDeskLog2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HelpDeskLog2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606022028473_HelpDeskLog2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
