// <auto-generated />
namespace SmartLabours.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HelpDeskLog1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HelpDeskLog1));
        
        string IMigrationMetadata.Id
        {
            get { return "201606021759508_HelpDeskLog1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
